# -*- coding: utf-8 -*-
"""enhancementAndEdge

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tMiyngCjrkTL7wai8bZn8Ha_InECwNwE
"""

# Import required libraries
import cv2
import numpy as np
import matplotlib.pyplot as plt
img = cv2.imread('/content/image.jpg')
img_resized = cv2.resize(img, (512, 512))
img_rgb = cv2.cvtColor(img_resized, cv2.COLOR_BGR2RGB)
img_yuv = cv2.cvtColor(img_resized, cv2.COLOR_BGR2YUV)
img_yuv[:, :, 0] = cv2.equalizeHist(img_yuv[:, :, 0])  # Histogram Equalization
img_enhanced = cv2.cvtColor(img_yuv, cv2.COLOR_YUV2RGB)
img_gray = cv2.cvtColor(img_resized, cv2.COLOR_BGR2GRAY)
edges = cv2.Canny(img_gray, 100, 200)
plt.figure(figsize=(15, 5))
plt.subplot(1, 3, 1)
plt.title("Original")
plt.imshow(img_rgb)
plt.axis('off')
plt.subplot(1, 3, 2)
plt.title("Enhanced")
plt.imshow(img_enhanced)
plt.axis('off')
plt.subplot(1, 3, 3)
plt.title("Edges")
plt.imshow(edges, cmap='gray')
plt.axis('off')
plt.tight_layout()
plt.show()

